### ISSUE TITLE
cannot compile on mac

### ISSUE THREAD

**Issue by eyvallah** [LucaFulchir/libRaptorQ#10]
i have compiled the lib with make and am using this command to compile the test_cpp_raw
`g++ test_cpp_raw.cpp -I../src -I../external/eigen3 -std=c++11 -o test_cpp_raw -L../lib -lRaptorQ`
but it keeps giving me error 
`Undefined symbols for architecture x86_64:
  "RaptorQ__v1::Impl::Operation::Block::~Block()", referenced from:
      RaptorQ__v1::Impl::Operation::Operation(RaptorQ__v1::Impl::Operation::_t, Eigen::Matrix<RaptorQ__v1::Impl::Octet, -1, -1, 1, -1, -1> const&) in test_cpp_raw-672800.o
  "RaptorQ__v1::Impl::Operation::Reorder::~Reorder()", referenced from:
      RaptorQ__v1::Impl::Operation::Operation(RaptorQ__v1::Impl::Operation::_t, std::__1::vector<unsigned short, std::__1::allocator<unsigned short> > const&) in test_cpp_raw-672800.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)`
but this command works on my ubuntu
i wonder what's wrong on my mac

**Comment by LucaFulchir** [comment]
uhm... by default on mac the cmake uses clang, but you are compiling the example with g++.
if you want to use g++ try launching the cmake with the appropriate option, for example:
> cmake -DCMAKE_C_COMPILER=gcc -DCAKE_CXX_COMPILER=g++ ../

Then you can use "make everything", "make examples", or just "make test_cpp_raw"

You can also use the "VERBOSE=1", as in:
> make VERBOSE=1 test_cpp_raw 
to see what the actual invocation was like.

You might also have problems in compiling by hand if you compiled RaptorQ with LZ4 supports and are not linking it in test_cpp_raw.

Can I ask you why you aren't useing the cmake?
I am trying to make it so it compiles even when you do stuff like that by hand, but I do not have a mac, so it is kinda hard at the moment.

**Comment by eyvallah** [comment]
oh actually i want to debug with xcode, well with a more visualized expression of knowing how the encoding and decoding process goes. when i tried to compile on xcode, the error shown are the same as i try to compile using this g++ command. yeah it's the problem of clang..

**Comment by LucaFulchir** [comment]
I'm looking into it, the file had some problems as it was a special case and not all constructors where correctly handled.

Try again, but please know that your previous compile command might give others errors as a lot of options are left unspecified.

**Comment by eyvallah** [comment]
it works 👍

**Comment by LucaFulchir** [comment]
Closing, and thanks for the report.
