### ISSUE TITLE
Getting started 

### ISSUE THREAD

**Issue by peererror** [LucaFulchir/libRaptorQ#11]
Hi is there any simple program to get start with the library

**Comment by LucaFulchir** [comment]
You can have a look at the test/ directory and the documentation.

**Comment by peererror** [comment]
Hi Thanks for the reply .Can I use this library to recover lost packets in udp ?

**Comment by LucaFulchir** [comment]
That is a possible usage, yes.
But please do not use the bugtracking for support requests, that should be left to mailing lists, irc or other.  
Closing since it's neither a feature request or a bug.
