### ISSUE TITLE
Symbol_Wrap write to const error

### ISSUE THREAD

**Issue by linux4life798** [LucaFulchir/libRaptorQ#12]
As a heads up, it looks like the `Symbol_Wrap` class has the wrong `const`-ness for it's `_raw` attribute.
In the [Interleaver.hpp](https://github.com/LucaFulchir/libRaptorQ/blob/master/src/RaptorQ/v1/Interleaver.hpp#L105) file.

The hunt began when I saw the following compilation error:
```
libRaptorQ/src/RaptorQ/v1/Interleaver.hpp:126:32: error: assignment of read-only location ‘static_cast<const uint8_t&>(((RFC6330__v1::Impl::Symbol_Wrap<T>*)this)->RFC6330__v1::Impl::Symbol_Wrap<T>::_raw[i])’
             _raw[i] ^= a._raw[i];
                                ^
```
Since the class seems to only modify the `uint8_t` values inside the array and not the pointer value itself, the `_raw` attribute could be `uint8_t *const _raw = nullptr;`.

Proposed changes:
* Change [line 156](https://github.com/LucaFulchir/libRaptorQ/blob/7b954e2110674b3c887b9faf6e585047cfab3042/src/RaptorQ/v1/Interleaver.hpp#L156) to `uint8_t *const _raw = nullptr;`
* Change the constructor args on [line 105](https://github.com/LucaFulchir/libRaptorQ/blob/7b954e2110674b3c887b9faf6e585047cfab3042/src/RaptorQ/v1/Interleaver.hpp#L105) to `Symbol_Wrap (uint8_t *raw, const uint16_t size) : _raw (raw),`

There may be other issues with this class(like setting equal different sized Symbol_Wraps), but those don't hold back the compilation process.

Best,

Craig

**Comment by LucaFulchir** [comment]
Yes, you are right, and actually the bug already is corrected in a private repo.

I need to take the time to port the changes the public repo.

There are actually lots of changes to be made so I should recommend using the old 0.1.X branch for now...

...I **really** need to port those. I'll try to invest as much time on it as I can this month.
...and while I'm at it, generate new gpg keys.

Thank you for your interest :)
I'll close this as soon as I can port those.

**Comment by linux4life798** [comment]
Awesome. I appreciate it!

Best,

Craig

**Comment by LucaFulchir** [comment]
Fixed, closing.
Will port other (really needed changes) when I can.

**Comment by linux4life798** [comment]
Awesome. Thanks!
