### ISSUE TITLE
Manual redefinition of ssize_t fails on macOS

### ISSUE THREAD

**Issue by harmony-ek** [LucaFulchir/libRaptorQ#18]
On macOS where both `long` and `long long` are 64 bits wide,

* `common.hpp` chooses `int64_t` as `ssize_t`;
* `int64_t` is defined as `long long`;
* `ssize_t` is already defined as `long`

So the typedef is non-idempotent, and gives a compilation error.

**Comment by harmony-ek** [comment]
I signed and sent a CLA your way last night; I will submit a PR once I receive the completed CLA.

**Comment by LucaFulchir** [comment]
Hello, you should have received the signed cla a few weeks back, any news?

Next month I **might** be able to get a small mac to finally test something there, but no promises yet.

**Comment by harmony-ek** [comment]
Hi, I just created #19 for it.  Thanks!

**Comment by LucaFulchir** [comment]
Merged.
It only took me... 3 years? personal record. Sorry.
