### ISSUE TITLE
[Windows] Thread_Pool is locked in destructor while waiting for finishing of pending _exiting threads

### ISSUE THREAD

**Issue by maxhora** [LucaFulchir/libRaptorQ#22]
The issue happens only on Windows (MSYS2 MinGW toolchain is used) and so far can't be reproduced with gcc on Linux or clang on MacOS.

For some reason a worker thread is not get unlocked by notify_all after a worker thread was moved to _exiting list of threads during call of `resize_pool (0, RaptorQ__v1::Work_State::ABORT_COMPUTATION);` inside `~Thread_Pool()`.

**Comment by LucaFulchir** [comment]
It's been a while and I never actually tested this on windows.  
I'll have a look at it this weekend.

I always found the RFC6330 API limiting though.  
I'll try to fix this but I'll renew my suggestion of using the RAW API, you have much more control there

**Comment by maxhora** [comment]
@LucaFulchir thank you for your reply,
I have built and run ` test_cpp_rfc` sample on Windows and so far the test sample works good and without mentioned issue.
