### ISSUE TITLE
Calling clear_data() in Encoder and reusing Encoder object for another

### ISSUE THREAD

**Issue by jontio** [LucaFulchir/libRaptorQ#24]
Sorry I couldn't add a bug report to gitlab when I tried I got this odd message `Signing in using your GitLab.com account without a pre-existing GitLab account is not allowed.` so I'll have to add this bug report to github.

When reusing the encoder class (C++11 header version of you code) git commit ae0c2fd for another input of data after calling `clear_data()` that causes an assertion in eigen3 when calling `compute_sync()` for the second time. I've tested both on windows `sys2` 64bit and linux 64bit x86 pcs and the same result. On windows I get this...

![image](https://user-images.githubusercontent.com/13667843/156309117-7549fd2a-0621-4a7c-b0f8-d5f9eec5b4f3.png)

on linux I get...

```
QRaptorQ::unencodedInput:
Bytes in: 34 symbols: 10 symbol size: 4
encoding time 0 ms
number of packets created = 40 each of size 6
encoding loading time 0 ms
"000AB99DF63C"
"000B195CD1DE"
"000C70EDE005"
"000D0E9D4C24"
"000E117BBBA2"
"000F4A9FC138"
"001089305A2C"
"0011EDD26B77"
QRaptorQ::unencodedInput:
Bytes in: 34 symbols: 10 symbol size: 4
untitled4: /usr/include/eigen3/Eigen/src/Core/Block.h:146: Eigen::Block<XprType, BlockRows, BlockCols, InnerPanel>::Block(XprType&, Eigen::Index, Eigen::Index, Eigen::Index, Eigen::Index) [with XprType = Eigen::Matrix<RaptorQ__v1::Impl::Octet, -1, -1, 1>; int BlockRows = -1; int BlockCols = -1; bool InnerPanel = false; Eigen::Index = long int]: Assertion `startRow >= 0 && blockRows >= 0 && startRow <= xpr.rows() - blockRows && startCol >= 0 && blockCols >= 0 && startCol <= xpr.cols() - blockCols' failed.
19:10:35: The program has unexpectedly finished.
```

The code snippet looks like this...

```C++
#include "RaptorQ/RaptorQ_v1_hdr.hpp"

using QRaptorQ_iterator = typename QByteArray::iterator;
using Encoder_type = RaptorQ::Impl::Encoder<QRaptorQ_iterator,QRaptorQ_iterator>;
using Decoder_type = RaptorQ::Impl::Decoder<QRaptorQ_iterator,QRaptorQ_iterator>;
using QRaptorQ_symbol_iterator = RaptorQ::It::Encoder::Symbol_Iterator<QRaptorQ_iterator,QRaptorQ_iterator>;

void QRaptorQ::unencodedInput(QByteArray &unencoded_input)
{
    qDebug()<<"QRaptorQ::unencodedInput:";

    if(encoder_future.valid())
    {
        qDebug()<<"dropping input data as we are waiting for encoder to finish";
        return;
    }

    //calc symbol size to fit in number of wanted blocks
    symbolSize=unencoded_input.size()/((int)blockSize);
    if((symbolSize*((int)blockSize))!=unencoded_input.size())symbolSize++;

    QElapsedTimer timer;
    timer.start();

    //re create encoder if block size is different
    if((encoder->symbols()!=(uint16_t)blockSize)||((int)encoder->symbol_size()!=symbolSize))
    {
        delete encoder;
        encoder=new Encoder_type(blockSize,symbolSize);
        qDebug()<<"creation time for encoder"<< timer.elapsed()<<"ms";
    }

    //give the input to the encoder. the encoder answers with the size of what it can use
    if((int)encoder->set_data(unencoded_input.begin(),unencoded_input.end())!=unencoded_input.size())
    {
        qDebug()<<"Could not give data to the encoder";
        return;
    }

    qDebug()<<"Bytes in:"<<unencoded_input.size()<<"symbols:"<<encoder->symbols()<<"symbol size:"<<encoder->symbol_size();

    encoder_future=std::async(std::launch::async,[this]
    {
        QElapsedTimer timer;
        timer.start();

        // RQ needs to do its magic on the input before you can ask the symbols.
        // multiple ways to do this are available.
        // The simplest is to run the computation and block everything until
        // the work has been done. Not a problem for small sizes (<200),
        // but big sizes will take **a lot** of time, consider running this with the
        // asynchronous calls
        if (!encoder->compute_sync())
        {
            // if this happens it's a bug in the library.
            // the **Decoder** can fail, but the **Encoder** can never fail.
            QMetaObject::invokeMethod(this,[this]()
            {
                qDebug()<<"encoder-RaptorQ failure! really bad!";
                if(encoder_future.valid())encoder_future.get();
            },Qt::QueuedConnection);
            return;
        }

        qDebug()<<"encoding time"<< timer.elapsed()<<"ms";
        timer.start();

        encodedOutputBytes.clear();
        QByteArray packet;
        packet.resize(symbolSize+2);

        uint32_t wanted_repairs=encoder->symbols()*4;
        uint32_t max_repair = encoder->max_repair();
        if(wanted_repairs>max_repair)wanted_repairs=max_repair;
        if(wanted_repairs>0xFFFF)wanted_repairs=0xFFFF;
        QRaptorQ_symbol_iterator encoder_symbol_iterator = encoder->begin_repair();
        for(;encoder_symbol_iterator!=encoder->end_repair(wanted_repairs);++encoder_symbol_iterator)
        {
            //get id
            uint32_t repair_id=(*encoder_symbol_iterator).id();
            packet[0]=(uint8_t)((repair_id>>8)&0xFF);
            packet[1]=(uint8_t)(repair_id&0xFF);
            //get repair symbol
            auto it = packet.begin()+2;
            auto written = (*encoder_symbol_iterator)(it, packet.end());
            if ((int)written != symbolSize)
            {
                QMetaObject::invokeMethod(this,[this,written]()
                {
                    qDebug()<<written<<"-vs-"<<symbolSize<<"Could not get the whole repair symbol!";
                    if(encoder_future.valid())encoder_future.get();
                },Qt::QueuedConnection);
                return;
            }
            encodedOutputBytes.push_back(packet);
        }

        qDebug()<<"number of packets created ="<<encodedOutputBytes.size()<<"each of size"<<packet.size();
        qDebug()<<"encoding loading time"<< timer.elapsed()<<"ms";

        //this will cause a assert then next time we
        //load and call encoder->compute_sync()
        encoder->clear_data();

        QMetaObject::invokeMethod(this,[this]()
        {
            //tell the user they can get packets now
            emit encodedOutputReady();
            if(encoder_future.valid())encoder_future.get();
        },Qt::QueuedConnection);

    });

}
```

Without calling `clear_data()` then I don't get the assertion but of cause I just get more  packets of the first message not the second one as wanted. So far the only way I can get around this is by deleting the the encoder object every time I want to make a new message encoding.

I'm also having similar problems with the decoder but haven't looked closely enough into it yet. So I'll keep this bug report just for the encoder.

Cheers,
Jonti

**Comment by LucaFulchir** [comment]
uhm... I tried modifying one of my example to run `compute_sync()/clear_data()/set_data()/compute_sync()` and I don't see the assert.

Can you please try to provide a minimal, compilable example? Honestly I never worked with QT so I'd rather not spend time learning it and the necessary includes for your snippet.

One thing to check: while I tried to make libRaptorQ generic over every iterator type, I remember having doubts on some parts, so try just `uint8_t*` as iterators, or usa a normal `std::vector<uint8_t>`.  
It has been a while and I don't remember if I fixed it all.

Also, you are not supposed to use the `::Impl::` stuff. Just use `RaptorQ::Encoder`

**Comment by jontio** [comment]
Strange. The simplest example I can think of fails on my windows and Linux computers.

I tried `std::vector<uint8_t>::iterator` but did not change things (`QByteArray::iterator` is `char*`). I did notice that when you get the repair/symbol iterator back from the encoder only `++it` works to move on but `it++` doesn't; that stumped me for a bit as I tent to use `++` after things.

I used `::Impl::` as qtcreator on my windows computer at least can't do auto complete without it; I'm not sure why.

This is the simplest example I can think of that fails that's not just a code snippet...

`untitled9.pro`
```qt
QT += core
QT -= gui
CONFIG += c++11
TARGET = untitled9
CONFIG += console
CONFIG -= app_bundle
TEMPLATE = app
SOURCES += main.cpp
#for RaptorQ it want's Eigen/Core but on windows
#at least that's eigen2/Eigen/Core
for(var, $$list($${QMAKE_DEFAULT_INCDIRS})) {
    new_inc_path_posibility=$$files($${var}/eigen3, false)
    !equals(new_inc_path_posibility,"") {
        #message( "eigen3 location is "$${new_inc_path_posibility} )
        INCLUDEPATH += $$new_inc_path_posibility
    }
}
DEFINES += QT_DEPRECATED_WARNINGS
```

`main.cpp`
```C++
#include<QDebug>
#include "RaptorQ/RaptorQ_v1_hdr.hpp"
namespace RaptorQ = RaptorQ__v1;
using QRaptorQ_iterator_Rnd = typename std::vector<uint8_t>::iterator;
using QRaptorQ_iterator_Fwd = typename std::vector<uint8_t>::iterator;
using Encoder_type = RaptorQ::Encoder<QRaptorQ_iterator_Rnd,QRaptorQ_iterator_Fwd>;
using Decoder_type = RaptorQ::Decoder<QRaptorQ_iterator_Rnd,QRaptorQ_iterator_Fwd>;
using QRaptorQ_symbol_iterator = RaptorQ::It::Encoder::Symbol_Iterator<QRaptorQ_iterator_Rnd,QRaptorQ_iterator_Fwd>;

int main(int argc, char *argv[])
{
    Q_UNUSED(argc);
    Q_UNUSED(argv);
    int my_size=10;
    RaptorQ::Block_Size blockSize=RaptorQ::Block_Size::Block_10;
    int symbolSize=2;
    Encoder_type *encoder=new Encoder_type(blockSize,symbolSize);
    std::vector<uint8_t> test_std_vec;
    test_std_vec.resize(my_size);

    encoder->set_data(test_std_vec.begin(),test_std_vec.end());
    encoder->compute_sync();
    encoder->clear_data();

    encoder->set_data(test_std_vec.begin(),test_std_vec.end());
    encoder->compute_sync();
    encoder->clear_data();

    delete encoder;
    return 0;
}
```

To compile and run type...

```
qmake
make
./untitled9
```

On Linux I get...

```bash
jontio@linux:~/untitled9$ ./untitled9
untitled9: /usr/include/eigen3/Eigen/src/Core/Block.h:146: Eigen::Block<XprType, BlockRows, BlockCols, InnerPanel>::Block(XprType&, Eigen::Index, Eigen::Index, Eigen::Index, Eigen::Index) [with XprType = Eigen::Matrix<RaptorQ__v1::Impl::Octet, -1, -1, 1>; int BlockRows = -1; int BlockCols = -1; bool InnerPanel = false; Eigen::Index = long int]: Assertion `startRow >= 0 && blockRows >= 0 && startRow <= xpr.rows() - blockRows && startCol >= 0 && blockCols >= 0 && startCol <= xpr.cols() - blockCols' failed.
Aborted (core dumped)
jontio@linux:~/untitled9$ 
```

To make the simplified code I used the other example and kept removing things from it. If I've done something wrong in this example I might have to supply some more lengthy code. I did wounder if it was a multi thread issue but this example just has the one thread so that's that idea out the window.

Cheers,
Jonti

**Comment by LucaFulchir** [comment]
Found the bug, fixed in master

Do note that just calling `compute_sync()` will reuse the Encoder object, but will not reuse the encoder precomputation.
You probably want to use `precompute_sync()` instead.

This was just about the encoder though, I did not look at anything on the decoder side.

Can you confirm if it works for you know?

**Comment by jontio** [comment]
Thanks for that.

I've tested that and yup that works fine.

I'm not sure the difference between `precompute_sync()` and `compute_sync()` both seems to produce valid packets. But I think the idea is that `precompute_sync()` is faster, not sure. But OK I'll use `precompute_sync()` from now on.

Yes I think a similar bug might be in the decoder but I haven't looked into that too much yet. Currently I've just been deleting both encoders and decoders every time I need to encode or decode a new block.

Cheers,
Jonti

**Comment by LucaFulchir** [comment]
Ok, I'll close this one for the encoder and maybe look at the decoder this weekend.

Basically `precompute_sunc()` will cache an intermediate matrix instead of redoing everything each time.  
The first time it might be a bit slower then just `compute_sync()` (you still won't notice on small blocksizes), but then it's much faster because it only need a matrix multiplication.

**Comment by jontio** [comment]
Hi Luca,

Thanks. I put some code together to test for the decoder bug here https://github.com/LucaFulchir/libRaptorQ/issues/15#issuecomment-1110356280 as it's part of that issue. I tried to keep the code as simple and as short as possible; I hope it's OK. It seems a similar bug, create the decoder on the heap, use it once, call `clear_data`, add symbols `add_symbol`, `wait_sync`, and then it returns `NEED_DATA`.

Cheers,
Jonti
