### ISSUE TITLE
cmake build failed.

### ISSUE THREAD

**Issue by bloomsource** [LucaFulchir/libRaptorQ#5]
cmake failed.

[root@localhost build]# cmake ..
-- libRaptorQ version 0.2-prealpha
-- Build selected: Release
-- Link Time Optimization activated
-- Profiling activated
-- Found git in /usr/bin/git
-- Found eigen3 in /root/libRaptorQ-master/external/eigen3
-- Could NOT find LATEX (missing:  LATEX_COMPILER) 
-- I could not find the latex command.
-- I could not find the pdflatex command.
-- I could not find the bibtex command.
-- I could not find the makeindex command.
-- I could not find the dvips command.
-- I could not find the ps2pdf command.
-- I could not find the pdftops command.
-- I could not find the latex2html command.
CMake Warning at CMakeLists.txt:134 (message):
  Not inside a git repository.  Compiler seed is now constant.

CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
RQ_LZ4_INCLUDE_DIR (ADVANCED)
   used as include directory in directory /root/libRaptorQ-master
   used as include directory in directory /root/libRaptorQ-master
   used as include directory in directory /root/libRaptorQ-master
   used as include directory in directory /root/libRaptorQ-master
   used as include directory in directory /root/libRaptorQ-master
   used as include directory in directory /root/libRaptorQ-master
   used as include directory in directory /root/libRaptorQ-master
   used as include directory in directory /root/libRaptorQ-master
   used as include directory in directory /root/libRaptorQ-master
   used as include directory in directory /root/libRaptorQ-master
   used as include directory in directory /root/libRaptorQ-master
   used as include directory in directory /root/libRaptorQ-master
   used as include directory in directory /root/libRaptorQ-master
   used as include directory in directory /root/libRaptorQ-master
   used as include directory in directory /root/libRaptorQ-master
   used as include directory in directory /root/libRaptorQ-master
   used as include directory in directory /root/libRaptorQ-master
   used as include directory in directory /root/libRaptorQ-master
   used as include directory in directory /root/libRaptorQ-master
   used as include directory in directory /root/libRaptorQ-master
   used as include directory in directory /root/libRaptorQ-master/doc
   used as include directory in directory /root/libRaptorQ-master/doc
   used as include directory in directory /root/libRaptorQ-master/doc
   used as include directory in directory /root/libRaptorQ-master/doc
   used as include directory in directory /root/libRaptorQ-master/doc
   used as include directory in directory /root/libRaptorQ-master/doc
   used as include directory in directory /root/libRaptorQ-master/doc

-- Configuring incomplete, errors occurred!
See also "/root/libRaptorQ-master/build/CMakeFiles/CMakeOutput.log".
See also "/root/libRaptorQ-master/build/CMakeFiles/CMakeError.log".

here is the tail of /root/libRaptorQ-master/build/CMakeFiles/CMakeError.log

#include

int main(int argc, char** argv)
{
(void)argv;
#ifndef pthread_create
return ((int*)(&pthread_create))[argc];
#else
(void)argc;
return 0;
#endif
}

Determining if the function pthread_create exists in the pthreads failed with the following output:
Change Dir: /root/libRaptorQ-master/build/CMakeFiles/CMakeTmp

Run Build Command:"/usr/bin/gmake" "cmTC_a589a/fast"
/usr/bin/gmake -f CMakeFiles/cmTC_a589a.dir/build.make CMakeFiles/cmTC_a589a.dir/build
gmake[1]: Entering directory `/root/libRaptorQ-master/build/CMakeFiles/CMakeTmp'
Building C object CMakeFiles/cmTC_a589a.dir/CheckFunctionExists.c.o
/usr/bin/cc -DCHECK_FUNCTION_EXISTS=pthread_create -o CMakeFiles/cmTC_a589a.dir/CheckFunctionExists.c.o -c /usr/local/share/cmake-3.5/Modules/CheckFunctionExists.c
Linking C executable cmTC_a589a
/usr/local/bin/cmake -E cmake_link_script CMakeFiles/cmTC_a589a.dir/link.txt --verbose=1
/usr/bin/cc -DCHECK_FUNCTION_EXISTS=pthread_create CMakeFiles/cmTC_a589a.dir/CheckFunctionExists.c.o -o cmTC_a589a -rdynamic -lpthreads
/usr/bin/ld: cannot find -lpthreads
collect2: error: ld returned 1 exit status
gmake[1]: *** [cmTC_a589a] Error 1

my environment is centos 7.2 , cmake 3.5
i am very sure that pthread library is installed, 
i install development tool kit with

yum groupinstall "Development Tools"

**Comment by LucaFulchir** [comment]
You might want to stick with the 0.1.6 tag release.
The master branch is for development, and APIs are gonna change really soon.
A big commit is pending due to some bug I have to track down.

Still, I'll look into this as soon as centos7.2 finishes installing...

**Comment by LucaFulchir** [comment]
The master branch can now generate, compress and store precomputed matrices in memory.
The storing/retrieving function is just a stub, so keep in mind it is *not* ready.
For compressing we need the LZ4 library.

In case the LZ4 library is not found on the system, we can use our, which we store in a git submodule.

I fixed the error message, in the latest commit, please try again.
Still, I did not find any problems with the pthread library.

**Comment by LucaFulchir** [comment]
Closing due to no news.
