### ISSUE TITLE
probability of decoding success

### ISSUE THREAD

**Issue by Sai-Jiang** [LucaFulchir/libRaptorQ#7]
Question 1:
I was bothered by zero return value from RaptorQ_decode().
Any tips? 
or what is the possible reason that cause this problem?
The number of symbols seems enough.

Question 2:
what is the probability of decoding success for now?
The RaptorQ technical overview has mentioned that 99.9999% from reception of K+2 encoded symbols.

Thx :)

**Comment by LucaFulchir** [comment]
Please use the mailing list, irc or write me for questions, bug reports are not really forums :)

Anyway, as the rfc goes, the probability is 1% without additional repair symbols,
and gets 100 times lower for each repair symbol.

The "libRaptorQ-test" binary is designed to test that...
but I can't do millions on computations on the bigger sizes, as they take simply too much.

I have tried to follow the rfc as best as I could, so things should be compliant.
There is also this paper: http://citeseerx.ist.psu.edu/viewdoc/summary?doi=10.1.1.432.4519
which tried to determine which repair symbols have to be dropped to block decoding.  
However If I remember correctly that was tested with OpenRQ, before they corrected a little
bug in their algorithm. So it is likely not entirely correct anymore.


I'd like to test the library against some well-known implementation, but I don't even know if there is an official implementation.  
The RFC was also really difficult to read, so I am afraid that each implementation might have their own little bugs in it.  
No money, no time.... can't really do better than this :(

**Comment by LucaFulchir** [comment]
closing due to no fedback
