### ISSUE TITLE
how can we verify that your decoding complexity is correct?

### ISSUE THREAD

**Issue by mjohn123** [LucaFulchir/libRaptorQ#8]
Thank you for sharing us a good implementation. As I read the paper, it said that RaptorQ using Interactivation decoding which has lower decoding complexity than Gaussian Elimination. However, I did not find any formula which estimates the complexity of Interactivation decoding. When you implement it, how you can verify that your decoding complexity is correct?  I read your document in Complexity section but it does not provide any formula for complexity of Interactivation decoding. Thank you so much

**Comment by Rubyko** [comment]
You can view the Gaussian elimination as a special case of inactivating decoding. Belief-propagation decoding is also a special case. The decoding complexity depends on a situation. E.g. if we are able to use belief-propagation then we use it, if not then we use gaussian elimination. It only depends on what symbols we have received.

**Comment by Rubyko** [comment]
More clear example. You must know that RaptorQ uses intermediate symbols to generate encoded symbols. Intermediate symbols are source symbols and redundant symbols. Redundant symbols are defined by XORing source symbols with redundant symbols so that it equals to 0 (constraint symbol).  In the case when we are receiving a source symbol we can start belief-propagation decoding with linear complexity. But it can be stopped as soon as there is no more solution. Belief-propagation decoding may be viewed as a BACK SUBSTITUTION. Different names but the meaning is the same.

**Comment by mjohn123** [comment]
Thank Rubyko, I know the interactivation is joint decoding between gaussian elimination and bp. In that view, we can said that it has lower complex than gaussian elimination. In thoery, the complexity of gaussian elimination can be estimated by O(n^3), how about the interactivatiom decoding? I did not find any theory formula of the complexity of interactivatiom decoding. I think this is difficult because the complexity depend on the number packets which can decode by BP. Secondy, you said that "Intermediate symbols are source symbols and redundant symbols." It looks wrong. The encoded symbol are source and redundant symbols, instead of intermediate symbols due to systematic properties. Thanks

**Comment by LucaFulchir** [comment]
I found one of the best explanations of the overall algorithm in:
<pre>
Raptor Codes
By Amin Shokrollahi and Michael Luby
Foundations and Trends in Communications and Information Theory
Vol. 6, Nos. 3–4 (2009) 213–322
2011 A. Shokrollahi and M. Luby
</pre>
(is this the paper you cited?)  
Although it might not be the formal complexity analysis you are looking for.

There are also improvements on the decoding algorithm, like in
"Low-Complexity Decoding for RaptorQ Codes Using a Recursive Matrix Inversion Formula"
But I do not have much time to try to implement all of that for now.

Let me know if you find something on those lines...

**Comment by mjohn123** [comment]
I read both papers and book but they did not show any analysis formula for 3GPP decoding standard which you used. Actually, the IEEE letter does not compare with 3GPP, he just compared with Gaussian Elimination (bad idea). The best one must be join BP and Gaussian Elimination method

**Comment by LucaFulchir** [comment]
No news in a long time and unfortunately I do not have the time for theory right now.

Can I close?

**Comment by ShawnshanksGui** [comment]
@LucaFulchir,
Thanks for your sharing of great implementation, can I think that  as AL-FEC, your RaptorQ code is state of art  implementation for sake of coding time complexity?,   
Because I fell so strange that some people show their RaptorQ coding time which is so low, ie, 10-20ms (N=250,k = 240, S=1024Bytes) in their papers, but according to your code' result, the time is almostly 80ms.   how to explain this phenomenon?

Thanks for your kind consideration!

Fei Gui

**Comment by LucaFulchir** [comment]
uhm... it might depend on the hardware, my benchmarks are on a 2012 laptop after all...
I have a core i7-3630QM, which is designed for laptops. If they used something server-oriented they might also benefit from bigger caches, which would make a big difference in the matrix operations.

Having a lot of disparity might also mean that my code is bad, that they have better optimizations, or that they implemented other papers, while libRaptorQ tight now implements just the basics.

I still think the whole complexity is correct, but I admit I have not seen benchmarks of other implementations that could prove or disprove this.

I would need to know at least which implementation we are talking about, or some reference on the hardware used.

**Comment by xin-at-marathon** [comment]
I just tested libRaptorQ and it turns out 100 times slower than the RS(Vandermonde) on both encoding and decoding.
But should Rapid Tornado code be faster according to the papers?!

**Comment by LucaFulchir** [comment]
@xin-at-marathon

RaptorQ id very sensitive depending on the block size so I can't really comment on the difference without some details.

I also have not run any benchmarks comparing it to other projects, can you share the details?
