### ISSUE TITLE
what's the meaning of alpha ^^ (i-j)?

### ISSUE THREAD

**Issue by plong009** [LucaFulchir/libRaptorQ#9]
about GAMMA, libRaptorQ is different than other implementations(like OpenRQ, raptorQ, velopyraptorQ),

in function make_GAMMA() of libRaptorQ:
GAMMA (row, col) = RaptorQ__v1::Impl::oct_exp[(row - col) % RaptorQ__v1::Impl::oct_exp.size()];
RaptorQ__v1::Impl::oct_exp.size() equals  510.

in the other implementations, they looks like this:
GAMMA (row, col) = RaptorQ__v1::Impl::oct_exp[(row - col) % 255];

the RFC document writes "GAMMA[i,j] = alpha ^^ (i-j)", actually I don't quite undstand it,
is the difference meaning?

**Comment by LucaFulchir** [comment]
Well, both are correct, actually.

In the RFC just before section 5.7.3:  
for  0 <= i < 256  alpha^^i == oct_exp[i]

So it would seem that the other implementations are correct.  But the oct_exp actually contains the same elements twice. oct_exp.size() is actually safe.  
I just pushed a commit to format a bit better the file with oct_exp and oct_log, you can easily see it now.

Performance-wise I don't know if there is a difference, even minimal (maybe cache usage?).  I might change it to be more uniform with the other implementations, though.

**Comment by LucaFulchir** [comment]
Committed the %255 change.
Closing.
